config/routes.rb
Rails.application.routes.draw do
  get 'suggest', to: 'search#suggest'
  get 'search',  to: 'search#index'
  root to: 'artists#index'
  resources :artists
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/album.rb
class Meta
  include Virtus.model

  attribute :rating
  attribute :have
  attribute :want
  attribute :formats
end

class Album
  include Elasticsearch::Persistence::Model

  index_name [Rails.application.engine_name, Rails.env].join('-')


  mapping _parent: { type: 'artist' } do
  end

  attribute :artist
  attribute :artist_id, String, mapping: { index: 'not_analyzed' }
  attribute :label, Hash, mapping: { type: 'object' }

  attribute :title
  attribute :released, Date
  attribute :notes
  attribute :uri

  attribute :tracklist, Array, mapping: { type: 'object' }

  attribute :styles
  attribute :meta, Meta, mapping: { type: 'object' }

  attribute :suggest, Hashie::Mash, mapping: {
    type: 'object',
    properties: {
      title: {
        type: 'object',
        properties: {
          input:   { type: 'completion' },
          output:  { type: 'keyword', index: false },
          payload: { type: 'object', enabled: false }
        }
      },
      track: {
        type: 'object',
        properties: {
          input:   { type: 'completion' },
          output:  { type: 'keyword', index: false },
          payload: { type: 'object', enabled: false }
        }
      }
    }
  }
end

app/models/artist.rb
class Artist
  include Elasticsearch::Persistence::Model

  index_name [Rails.application.engine_name, Rails.env].join('-')

  analyzed_and_raw = { fields: {
    name: { type: 'text', analyzer: 'snowball' },
    raw:  { type: 'keyword' }
  } }

  attribute :name, String, mapping: analyzed_and_raw

  attribute :profile
  attribute :date, Date

  attribute :members, String, default: [], mapping: analyzed_and_raw
  attribute :members_combined, String, default: [], mapping: { analyzer: 'snowball' }

  attribute :urls, String, default: []
  attribute :album_count, Integer, default: 0

  attribute :suggest, Hashie::Mash, mapping: {
    type: 'object',
    properties: {
      name: {
        type: 'object',
        properties: {
          input:   { type: 'completion' },
          output:  { type: 'keyword', index: false },
          payload: { type: 'object', enabled: false }
        }
      },
      member: {
        type: 'object',
        properties: {
          input:   { type: 'completion' },
          output:  { type: 'keyword', index: false },
          payload: { type: 'object', enabled: false }
        }
      }
    }
  }

  validates :name, presence: true

  def albums
    Album.search(
      { query: {
          has_parent: {
            type: 'artist',
            query: {
              bool: {
                filter: {
                  ids: { values: [ self.id ] }
                }
              }
            }
          }
        },
        sort: 'released',
        size: 100
      },
      { type: 'album' }
  )
  end

  def to_param
    [id, name.parameterize].join('-')
  end
end

app/models/suggester.rb
class Suggester
  attr_reader :response

  def initialize(params={})
    @term = params[:term]
  end

  def response
    @response ||= begin
      #
      # http://www.rubydoc.info/gems/elasticsearch-api/Elasticsearch/API/Actions#search-instance_method
      # https://www.elastic.co/guide/en/elasticsearch/reference/current/search-request-body.html
      # https://www.elastic.co/guide/en/elasticsearch/reference/current/search-suggesters-completion.html
      #
      Elasticsearch::Persistence.client.search \
      index: Artist.index_name,
      body: {
        suggest: {
          artists: {
            text: @term,
            completion: { field: 'suggest.name.input', size: 25 }
          },
          members: {
            text: @term,
            completion: { field: 'suggest.member.input', size: 25 }
          },
          albums: {
            text: @term,
            completion: { field: 'suggest.title.input', size: 25 }
          },
          tracks: {
            text: @term,
            completion: { field: 'suggest.track.input', size: 25 }
          }
        },
        _source: ['suggest.*']
      }
    end
  end

  def as_json(options={})
    return [] unless response['suggest']

    output = [
      { label: 'Bands',
        value: response['suggest']['artists'][0]['options'].map do |d|
          { text: d['_source']['suggest']['name']['output'],
            url:  d['_source']['suggest']['name']['payload']['url'] }
        end
      },

      { label: 'Albums',
        value: response['suggest']['albums'][0]['options'].map do |d|
          { text: d['_source']['suggest']['title']['output'],
            url:  d['_source']['suggest']['title']['payload']['url'] }
        end
      },

      { label: 'Band Members',
        value: response['suggest']['members'][0]['options'].map do |d|
          { text: "#{d['text']} (#{d['_source']['suggest']['member']['output']})",
            url:  d['_source']['suggest']['member']['payload']['url'] }
        end
      },

      { label: 'Album Tracks',
        value: response['suggest']['tracks'][0]['options'].map do |d|
          { text: "#{d['text']} (#{d['_source']['suggest']['track']['output']})",
            url:  d['_source']['suggest']['track']['payload']['url'] }
        end
      }
    ]
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/artists_controller.rb
class ArtistsController < ApplicationController
  before_action :set_artist, only: [:show, :edit, :update, :destroy]

  rescue_from Elasticsearch::Persistence::Repository::DocumentNotFound do
    render file: "public/404.html", status: 404, layout: false
  end

  def index
    @artists = Artist.all sort: 'name.raw', _source: ['name', 'album_count']
  end

  def show
    @albums = @artist.albums
  end

  def new
    @artist = Artist.new
  end

  def edit
  end

  def create
    @artist = Artist.new(artist_params)

    respond_to do |format|
      if @artist.save refresh: true
        format.html { redirect_to @artist, notice: 'Artist was successfully created.' }
        format.json { render :show, status: :created, location: @artist }
      else
        format.html { render :new }
        format.json { render json: @artist.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @artist.update(artist_params, refresh: true)
        format.html { redirect_to @artist, notice: 'Artist was successfully updated.' }
        format.json { render :show, status: :ok, location: @artist }
      else
        format.html { render :edit }
        format.json { render json: @artist.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @artist.destroy refresh: true
    respond_to do |format|
      format.html { redirect_to artists_url, notice: 'Artist was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    def set_artist
      @artist = Artist.find(params[:id].split('-').first)
    end

    def artist_params
      a = params.require(:artist)
      a[:members] = a[:members].split(/,\s?/) unless a[:members].is_a?(Array) || a[:members].blank?
      return a
    end
end

app/controllers/search_controller.rb
class SearchController < ApplicationController

  def index
    tags = { pre_tags: '<em class="hl">', post_tags: '</em>' }
    @artists = Artist.search \
      query: {
        multi_match: {
          query: params[:q],
          fields: ['name^10','members^2','profile']
        }
      },
      highlight: {
        tags_schema: 'styled',
        fields: {
          name:    { number_of_fragments: 0 },
          members_combined: { number_of_fragments: 0 },
          profile: { fragment_size: 50 }
        }
      }

    @albums = Album.search \
      query: {
        multi_match: {
          query: params[:q],
          fields: ['title^100','tracklist.title^10','notes^1']
        }
      },
      highlight: {
        tags_schema: 'styled',
        fields: {
          title: { number_of_fragments: 0 },
          'tracklist.title' => { number_of_fragments: 0 },
          notes: { fragment_size: 50 }
        }
      }
  end

  def suggest
    render json: Suggester.new(params)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/artists_helper.rb
module ArtistsHelper
end

app/helpers/search_helper.rb
module SearchHelper

  def highlight(object, field)
    object.try(:hit).try(:highlight).try(field)
  end

  def highlighted(object, field)
    if h = object.try(:hit).try(:highlight).try(field).try(:first)
      h.html_safe
    else
      field.to_s.split('.').reduce(object) { |result,item| result.try(item) }
    end
  end

end

app/views/artists/_form.html.erb
<%= simple_form_for @artist do |f| %>
  <%= f.input :name %>
  <%= f.input :profile, as: :text %>
  <%= f.input :date, as: :date %>
  <%= f.input :members, hint: 'Separate names by comma', input_html: { value: f.object.members.join(', ') } %>

  <%= f.button :submit %>
<% end %>

app/views/artists/edit.html.erb
<h1>Editing Artist</h1>

<%= render 'form', artist: @artist %>

<%= link_to 'Show', @artist %> |
<%= link_to 'Back', artists_path %>

app/views/artists/index.html.erb
<header>
  <h1>
    Artists
    <%= button_to 'New Artist', new_artist_path, method: 'get', tabindex: 5 %>
  </h1>
</header>

<section id="searchbox">
<%= form_tag search_path, method: 'get' do %>
  <input type="text" name="q" value="<%= params[:q] %>" id="q" autofocus="autofocus" placeholder="start typing to search..." tabindex="0" />
<% end %>
</section>

<section class="artists">
  <% @artists.each do |artist| %>
    <%= div_for artist, class: 'result clearfix' do %>
      <h2>
        <%= image_tag "http://ruby.elastic.co.s3-website-us-east-1.amazonaws.com/demo/music/bands/#{artist.id}.jpeg", height: '50px', class: 'band' %>
        <%= link_to artist do %>
          <span class="name"><%= artist.name %></span>
          <small><%= pluralize artist.album_count, 'album' %></small>
        <% end %>
      </h2>
      <div class="actions clearfix">
        <%= button_to 'Edit', edit_artist_path(artist), method: 'get' %>
        <%= button_to 'Destroy', artist, method: :delete, data: { confirm: 'Are you sure?' } %>
      </div>
    <% end %>
  <% end %>
</section>

<% if @artists.empty? %>
<section class="no-results">
  <p>The search hasn't returned any results...</p>
</section>
<% end %>

<script>
$.widget( "custom.suggest", $.ui.autocomplete, {
    _renderMenu: function( ul, items ) {
      $.each( items, function( index, item ) {
        var category = ul.append( "<li class='ui-autocomplete-category'>" + item.label + "</li>" );

        $.each( item.value, function( index, item ) {
          var li = $('<li class="ui-autocomplete-item"><a href="<%= Rails.application.config.relative_url_root %>'+ item.url +'">'+ item.text +'</a></li>').data('ui-autocomplete-item', item )
          category.append(li)
        } )
      });
    }
  });

$( "#q" ).suggest({
  source: '<%= suggest_path %>',
  select: function(event, ui) {
    document.location.href = '<%= Rails.application.config.relative_url_root %>'+ui.item.url
  }
});
</script>

<script>$('img.band').error(function(){ $(this).attr('src', '/images/blank_artist.png'); });</script>

app/views/artists/new.html.erb
<h1>New Artist</h1>

<%= render 'form', artist: @artist %>

<%= link_to 'Back', artists_path %>

app/views/artists/show.html.erb
<div class="artist">
  <header>
    <h1>
      <span class="back"><%= link_to "〈".html_safe, artists_path, title: "Back" %></span>
      <%= image_tag "http://ruby.elastic.co.s3-website-us-east-1.amazonaws.com/demo/music/bands/#{@artist.id}.jpeg", height: '50px', class: 'band' %>
      <%= @artist.name %>
      <%= button_to 'Edit', edit_artist_path(@artist), method: 'get' %>
    </h1>
  </header>

  <p id="notice"><%= notice %></p>

  <section class="artist-info">
    <span><%= @artist.members.to_sentence last_word_connector: ' and ' %></span> |
    <span><%= pluralize @albums.size, 'album' %></span>
    <p class="artist-profile"><%= @artist.profile %></p>
  </section>

  <section class="albums">
    <% @albums.each do |album| %>
    <%= div_for album, class: 'clearfix' do %>
        <h3>
          <span class="title"><%= album.title %></span>
          <div class="info">
            <small><%= album.meta.formats.join(', ') %></small>
            <small><%= album.released %></small>
          </div>
        </h3>

        <div class="cover">
          <%= image_tag "http://ruby.elastic.co.s3-website-us-east-1.amazonaws.com/demo/music/covers/#{album.id}.jpeg", width: '100px', class: 'cover' %>
        </div>

        <div class="content">
          <% album.tracklist.in_groups_of(album.tracklist.size/2+1).each_with_index do |half, g| %>
            <ul class=<%= cycle 'first', 'second' %> start="<%= g < 1 ? 1 : album.tracklist.size/2+2 %>">
              <% half.compact.each_with_index do |track, i| %>
                <li>
                  <i class="counter"><%= g < 1 ? i+1 : i+(g*album.tracklist.size/2+2)  %></i>
                  <%= track['title'] %>
                  <small><%= track['duration'] %></small>
                </li>
              <% end %>
            </ul>
          <% end %>
        </div>
      <% end %>

    <% end %>

    <script>$('img').error(function(){ $(this).attr('src', '/images/blank_cover.png'); });</script>
    <script>$(document.location.hash).effect('highlight', 1500)</script>
  </section>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Music</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body class="<%= controller.action_name %>">
    <%= yield %>
  </body>
</html>

app/views/search/index.html.erb
<header>
  <h1>
    <span class="back"><%= link_to "〈".html_safe, :back, title: "Back" %></span>
    Artists &amp; Albums
  </h1>
</header>

<section id="searchbox">
<%= form_tag search_path, method: 'get' do %>
  <input type="text" name="q" value="<%= params[:q] %>" id="q" autofocus="autofocus" placeholder="start typing to search..." tabindex="0" />
<% end %>
</section>

<section class="artists">
  <% @artists.each do |artist| %>
    <%= content_tag :div, class: 'artist search result clearfix' do %>
      <h2>
        <%= image_tag "http://ruby.elastic.co.s3-website-us-east-1.amazonaws.com/demo/music/bands/#{artist.id}.jpeg", height: '45px', class: 'band' %>
        <%= link_to artist do %>
          <span class="name"><%= highlighted(artist, :name) %></span>
          <small><%= pluralize artist.album_count, 'album' %></small>
        <% end %>
      </h2>
      <% if highlight = highlight(artist, :members_combined) %>
      <p class="highlight small">
        <span class="label">Members</span>
        <%= highlight.first.html_safe %>
      </p>
      <% end %>
      <% if highlight = highlight(artist, :profile) %>
      <p class="highlight small">
        <span class="label">Profile</span>
        <%= highlight.join('&hellip;').html_safe %>
      </p>
      <% end %>
    <% end %>
  <% end %>
</section>

<section class="albums">
  <% @albums.each do |album| %>
    <%= content_tag :div, class: 'album search result clearfix' do %>
      <h2>
        <%= image_tag "http://ruby.elastic.co.s3-website-us-east-1.amazonaws.com/demo/music/covers/#{album.id}.jpeg", width: '45px', class: 'cover' %>
        <%= link_to artist_path(album.artist_id, anchor: "album_#{album.id}") do %>
          <span class="name"><%= highlighted(album, :title) %></span>
          <small><%= album.artist %></small>
          <small>(<%= [album.meta.formats.first, album.released].compact.join(' ') %>)</small>
        <% end %>
      </h2>

      <% if highlight = highlight(album, 'tracklist.title') %>
        <p class="highlight small">
          <span class="label">Tracks</span>
          <%= highlight.join('&hellip;').html_safe %>
        </p>
      <% end %>

      <% if highlight = highlight(album, :notes) %>
        <p class="highlight small">
          <span class="label">Notes</span>
          <%= highlight.map { |d| d.gsub(/^\.\s?/, '') }.join('&hellip;').html_safe %>
        </p>
      <% end %>
    <% end %>
  <% end %>
</section>

<% if @artists.empty? && @albums.empty? %>
<section class="no-results">
  <p>The search hasn't returned any results...</p>
</section>
<% end %>

<script>
$.widget( "custom.suggest", $.ui.autocomplete, {
    _renderMenu: function( ul, items ) {
      $.each( items, function( index, item ) {
        var category = ul.append( "<li class='ui-autocomplete-category'>" + item.label + "</li>" );

        $.each( item.value, function( index, item ) {
          var li = $('<li class="ui-autocomplete-item"><a href="<%= Rails.application.config.relative_url_root %>'+ item.url +'">'+ item.text +'</a></li>').data('ui-autocomplete-item', item )
          category.append(li)
        } )
      });
    }
  });

$( "#q" ).suggest({
  source: '<%= suggest_path %>',
  select: function(event, ui) {
    document.location.href = '<%= Rails.application.config.relative_url_root %>'+ui.item.url
  }
});
</script>